# Generated by Django 2.2.2 on 2019-06-25 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('alias', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(unique=True)),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=32)),
                ('destiny', models.CharField(max_length=32)),
                ('start_time', models.DateTimeField(max_length=32)),
                ('end_time', models.DateTimeField(max_length=32)),
                ('comment', models.TextField()),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trans.Driver')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trans.Truck')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=32)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('p', 'PENDING'), ('d', 'PAID'), ('c', 'CANCELED')], max_length=16)),
                ('comment', models.CharField(max_length=128)),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trans.Freight')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('p', 'PENDING'), ('d', 'PAID'), ('c', 'CANCELED')], max_length=16)),
                ('comments', models.TextField()),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='trans.Freight')),
            ],
        ),
    ]
