# Generated by Django 2.2.2 on 2019-06-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freight',
            name='end_time',
            field=models.DateField(max_length=32),
        ),
        migrations.AlterField(
            model_name='freight',
            name='start_time',
            field=models.DateField(max_length=32),
        ),
    ]
